# Generated by Django 4.2 on 2023-04-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="pub_data", new_name="pub_date",
        ),
    ]
